name = "tts" 
main = "index.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]


workers_dev = false
route = { pattern = "tts.10091996.xyz", custom_domain = true }


[env.production]
name = "tts-voice-magic"
workers_dev = false
route = { pattern = "tts.10091996.xyz", custom_domain = true }

[env.staging]
name = "tts-voice-magic-staging"


[vars]


[triggers]
crons = []
